defmodule Tabletop.Repo.Migrations.SplitCardsAndPrints do
  use Ecto.Migration

  def up do
    # Existing cards will be regenerated by the importer after this migration.
    execute "DELETE FROM cards"

    drop_if_exists index(:cards, [:image_phash])
    drop_if_exists unique_index(:cards, [:print_id])

    alter table(:cards) do
      remove :print_id
      remove :image_url
      remove :image_phash
      remove :set_code
      add :external_card_id, :string
    end

    create unique_index(:cards, [:external_card_id])

    create table(:card_prints) do
      add :card_id, references(:cards, type: :binary_id, on_delete: :delete_all), null: false
      add :face_id, :string, null: false
      add :set_code, :string
      add :art_type, :string
      add :orientation, :string
      add :layout_position, :integer
      add :is_canonical, :boolean, default: true, null: false
      add :image_url, :string
      add :art_bbox, :map
      add :image_phash, :bigint
      add :image_phash_left, :bigint
      add :image_phash_right, :bigint
      add :image_phash_full, :bigint

      timestamps(type: :utc_datetime)
    end

    create unique_index(:card_prints, [:face_id])
    create index(:card_prints, [:card_id])
    create index(:card_prints, [:card_id, :is_canonical])
    create index(:card_prints, [:set_code])
    create index(:card_prints, [:image_phash])
    create index(:card_prints, [:image_phash_left])
    create index(:card_prints, [:image_phash_right])
    create index(:card_prints, [:image_phash_full])
  end

  def down do
    drop table(:card_prints)

    drop_if_exists unique_index(:cards, [:external_card_id])

    alter table(:cards) do
      remove :external_card_id
      add :print_id, :string
      add :image_url, :string
      add :image_phash, :bigint
      add :set_code, :string
    end

    create unique_index(:cards, [:print_id])
    create index(:cards, [:image_phash])
  end
end
