defmodule Tabletop.Repo.Migrations.DropCardPrintPhashHalves do
  use Ecto.Migration

  # Left/right half pHashes are gone: horizontal cards are now rotated to
  # portrait and matched via the single `image_phash` (art) + `image_phash_full`
  # arms, the same as vertical cards. Existing rows are regenerated by a full
  # re-import after this migration.
  def up do
    drop_if_exists index(:card_prints, [:image_phash_left])
    drop_if_exists index(:card_prints, [:image_phash_right])

    alter table(:card_prints) do
      remove :image_phash_left
      remove :image_phash_right
    end
  end

  def down do
    alter table(:card_prints) do
      add :image_phash_left, :bigint
      add :image_phash_right, :bigint
    end

    create index(:card_prints, [:image_phash_left])
    create index(:card_prints, [:image_phash_right])
  end
end
