# fly.toml app configuration file generated for fabtabletop on 2026-04-10T14:19:03+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fabtabletop'
primary_region = 'iad'

[build]
  dockerfile = '../Dockerfile'

[env]
  ECTO_IPV6 = 'true'
  PHX_HOST = 'fabtabletop.fly.dev'
  PHX_SERVER = 'true'
  PORT = '4000'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256